language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: aCG39xHFW7lJcZJo3/y6U8owC7pt/mAlxcxw9IrHHJJtMnCKK1cMEJZ7QEs0dydk7fflEKke48TaSmUWGESYVFbklLlRbbjjaEmiA5Z0aTPU21swOngJvIR8zEOz6zzfX6Qqi37ATAsSqJc3JFqDMRxVvG/7qWSM+dJMtOtGydAfQ35eo99STkw/wDNQn+V1ps8kgjnMIgU/gC6xksPe2+CKsXaindTmGNj5/AcazV5TKUKjdEA1djDHIsR+6uLkN99GiZa0IR3iUU2RsyGPdIsp5pLa3Lr6enLo/qffnFxvAjd0163PGX1OyZ/kmIqMtFUBvmvUUmhJHZHGyG5m3eSzZ2Y3DYDAcPD2GSAKayxnCVszrTb05/liABp8iG/OxphwUcKe+KI6VqERQ2L+ZpDO0UHUk4dfxubR06giKUA0mODIZKI34ZyxamKiPRjFW+z2Qacr40ApVBCv5MDDRklj3rgUIt9Vgg6PdecLmmF47HW/mVCpljB0DaFRD1Ggbw/nAiDe+hLUdYbtGgZ98R3lRDYLzg1/fDPanlzjo7psfOC4iIdmUr3szHQFlHWpRmRCaIonvxIY1ui6oI0UU+Z8/ZSlkNIHplZUiUIWAuV0y8+yW62eXE5QLhc2H0oYZIEQLW384ZyHI7/jDFsDkypRsW8nszRDyy8+PuQGIN4=
